# .circleci/config.yml

version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  build_testnet:
    macos:
      xcode: 11.5.0 # Specify the Xcode version to use
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
    steps:
      - checkout

      - node/install:
          node-version: "10.16.3"
          install-yarn: true
      # Download and cache dependencies
      # - restore_cache:
      #    keys:
      #      - v1-dependencies-{{ checksum "package.json" }}
      #      # fallback to using the latest cache if no exact match is found
      #      - v1-dependencies-

      - run: cp env/default.json.example env/default.json

      - run: yarn cache clean && yarn install --network-concurrency 1

      # - save_cache:
      #    paths:
      #      - node_modules
      #    key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd ios && bundle install

      - run: cd ios && bundle exec pod install

      - run:
          name: Fastlane
          command: cd ios && export BUILD_NUMBER=${CIRCLE_BUILD_NUM}00 && export VERSION_NUMBER=v3.0.${BUILD_NUMBER}-testnet && bundle exec fastlane $FASTLANE_LANE

      - store_artifacts:
          path: ios/output
      - store_test_results:
          path: ios/output/scan

workflows:
  version: 2
  build_testnet_and_mainnet:
    jobs:
      - build_testnet
